name: Hotfix Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Base release version to fix (e.g. 2)"
        required: true
        type: string

jobs:
  hotfix:
    runs-on: ubuntu-latest
    env:
      REGISTRY: cr.yandex/${{ secrets.REGISTRY_ID }}
      IMAGE: cr.yandex/${{ secrets.REGISTRY_ID }}/app
      HOTFIX_VERSION: ${{ github.run_number }}

    steps:
      - name: Checkout main branch first
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Checkout release branch
        run: |
          git fetch origin releases/${{ inputs.version }}
          git checkout releases/${{ inputs.version }}
          git pull origin releases/${{ inputs.version }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: |
          npm run lint
          npm run test

      - name: Build Docker image
        run: |
          docker build -t $IMAGE:${{ inputs.version }}_fix$HOTFIX_VERSION .
          docker tag $IMAGE:${{ inputs.version }}_fix$HOTFIX_VERSION $IMAGE:${{ inputs.version }}_latest

      - name: Login to Yandex Container Registry
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: iam
          password: ${{ secrets.YC_TOKEN }}

      - name: Push Docker images
        run: |
          docker push $IMAGE:${{ inputs.version }}_fix$HOTFIX_VERSION
          docker push $IMAGE:${{ inputs.version }}_latest

      - name: Create hotfix tag
        run: |
          git tag v${{ inputs.version }}-fix$HOTFIX_VERSION
          git push origin v${{ inputs.version }}-fix$HOTFIX_VERSION

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Find release issue
        id: find_issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=$(gh issue list --search "Release ${{ inputs.version }}" --json number --jq '.[0].number')
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT

      - name: Add hotfix comment
        if: steps.find_issue.outputs.issue_number != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment ${{ steps.find_issue.outputs.issue_number }} --body "
          ### 🔧 Hotfix Applied
          **Base Version:** ${{ inputs.version }}  
          **Hotfix Number:** $HOTFIX_VERSION  
          **Fixed by:** ${{ github.actor }}  
          **Date:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')  
          **Docker Image:** $IMAGE:${{ inputs.version }}_fix$HOTFIX_VERSION  

          To deploy this hotfix run the [Deploy workflow](https://github.com/${{ github.repository }}/actions/workflows/deploy.yml) with version: ${{ inputs.version }}
          "
